version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - pip install requests -t
      - pip install requests-aws4auth -t
  build:
    commands:
      - aws cloudformation package --template-file "Search Function/search-function.yaml" --s3-bucket artifactspgpcc --output-template-file search.yaml

artifacts:
  type: zip
  files:
    - search-function.yaml
    - search.yaml
